### ISSUE TITLE
Reparar erro de recuperação das fichas terminológicas de registros de qualificadores

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#105]
Boa tarde, @viniciusandrade e @marcoslmori! 

Em 19 de janeiro de 2024 recebemos a primeira notificação de que não estão sendo recuperadas as fichas terminológicas dos qualificadores. Em 26 de janeiro, a Laís recebeu comunicação do mesmo problema de um usuário do Fi-Admin para indexação.
Não conseguimos a visualização de nenhum registro de qualificador. Quando o qualificador possui algum termo em comum com outro qualificador (por exemplo, diagnóstico aparece em dois registros de qualificador), a pesquisa no site traz resultado. Entretanto, quando se tenta abrir os registros vindos na pesquisa, não é possível visualizar nenhuma ficha terminológica dos registros.
Pela visão hierárquica todos os descritores são visualizáveis, mas clicar em cada um deles não traz nenhum resultado.
Por favor, veja vídeo anexado.

https://github.com/bireme/Gestao-DeCS/assets/35345406/d13d1588-9496-4fb2-b6bc-3b260021a86e

Obrigada pela atenção!

**Comment by viniciusandrade** [comment]
Oi @acecampos, realizei ajustes no código em ambiente de testes e peço a gentileza de realizar a validação para solicitarmos ao @marcoslmori a atualização do ambiente de produção.

Exemplo de chamada:
https://decs.teste.bvsalud.org/ths/resource/?id=22010&filter=ths_qualifall&q=citologia

Obrigado

**Comment by lucianaPRB** [comment]
Anteriormente, problemas semelhantes foram identificados em:

**Comment by acecampos** [comment]
Oi, @viniciusandrade:
Validado no ambiente de testes.
Agradeço!

**Comment by viniciusandrade** [comment]
Obrigado @acecampos.

@marcoslmori favor proceder com a atualização do ambiente de produção. Grato.

**Comment by lucianaPRB** [comment]
Identifiquei que o qualificador exclusivo DeCS "políticas" é recuperado normalmente:
![image](https://github.com/bireme/Gestao-DeCS/assets/93340661/8f3f067c-2913-486b-80a1-572e78286763)
Os demais não são apresentados em pesquisas.

**Comment by acecampos** [comment]
Obrigada, @lucianaPRB. Interessante é que /politicas é exclusivo do DeCS.

**Comment by acecampos** [comment]
@viniciusandrade Não está funcionando nos outros idiomas.

**Comment by viniciusandrade** [comment]
@acecampos poderia detalhar melhor? Fiz um teste aqui e aparentemente esta OK:

![image](https://github.com/bireme/Gestao-DeCS/assets/349287/95b3014f-3bfe-44fd-b188-606ec85a1f58)

**Comment by acecampos** [comment]
@viniciusandrade ni, não estou conseguindo acessar o decs.teste agora.

**Comment by acecampos** [comment]
@viniciusandrade PERDÃO!!! Eu estava no decs.bvsalud.org de PRODUÇÃO!

**Comment by marcoslmori** [comment]
Enfim, podemos atualizar para a produção o plugin?

**Comment by viniciusandrade** [comment]
Sim @marcoslmori favor atualizar o plugin em produção.

**Comment by marcoslmori** [comment]
Plugin atualizado na produção e validado junto a @acecampos, @viniciusandrade e Jocevaldo, Para finalizar todo o processo é necessário executar um procedimento para limpeza/criação dos novos qualificadores através desse process : https://paho.sharepoint.com/:v:/r/sites/BIR/TC/TC/Gerencias/PFI/Suporte%20T%C3%A9cnico/DECS/limpeza-criarnovocache.mp4?csf=1&web=1&e=lQ47Vs

**Comment by acecampos** [comment]
@viniciusandrade, @marcoslmori e @jocevaldo Obrigada; vou executá-lo e quando terminar, fecho o issue.

**Comment by acecampos** [comment]
Obrigada! Vou proceder conforme combinado e fechar o issue assim que terminar.
