### ISSUE TITLE
2.1 Verificação de códigos hierárquicos órfãos @apendindan

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#110]

**Comment by acecampos** [comment]
Bom dia, @apendindan! Favor dar início à verificação dos códigos hierárquicos órfãos.

**Comment by acecampos** [comment]
@lucianaPRB, para acompanhamento

**Comment by apendindan** [comment]
@acecampos segue relatório com a lista dos códigos órfãos identificados via processamento: 
[LISTA_ORFAOS.txt](https://github.com/bireme/Gestao-DeCS/files/14485016/LISTA_ORFAOS.txt)

**Comment by acecampos** [comment]
@apendindan, agradeço a confecção da lista.
Os órfãos foram identificados e seus códigos hierárquicos, corrigidos.

Foram identificados dois registros que são do tesauro da FUNASA, que têm uma grande parte semelhante à subcategoria SP4. 

descriptor_ui	tree_number	term_string
DDCS026147	HP4.018.602.500.233.538	Bismuthum Metallicum => ok
DDCS026149	HP4.018.602.500.233.699	Bismuthum Oxydatum => ok
DDCS026150	HP4.018.602.500.233.815	Bismuthum Valerianicum => ok
D027882	HP4.018.602.600.023.156	Agave => ok
DDCS025927	HP4.018.602.600.023.837	Agave tequilana => ok
DDCS026060	HP4.018.602.600.094.271	Arum dracontium => ok
DDCS027649	HP4.018.700.745	Vaccininum => ok
**DFNS000066**	SP1.011.122.158	Program Evaluation => ok FUNASA
DDCS060737	SP2.840.566.433.340	Telepharmacy => ok
D000095882	SP2.840.566.433.780	Mental Health Teletherapy => ok
**DFNS000720**	SP4.122.006.052.463.639	Environmental Research => ok FUNASA

Assim, para registro, sugiro executar um filtro que não traga códigos hierárquicos começando com DFNS.

**Comment by acecampos** [comment]
Por favor, @apendindan, executar a conferência de códigos hierárquicos novamente, a fim de constatar se os órfãos foram zerados efetivamente.

**Comment by apendindan** [comment]
@acecampos Segue o resultado do processamento após suas correções. 
[LISTA_ORFAOS.txt](https://github.com/bireme/Gestao-DeCS/files/14495373/LISTA_ORFAOS.txt)

Os únicos detectados foram os DFNS, visto que o filtro ainda não foi colocado. Então imagino que significa que os órfão que podemos encontrar através desse script foram zerados.

**Comment by apendindan** [comment]
Segue lista de etapas para geração do relatório: 
- Atualização do Ambiente de Teste ([Documentação](https://github.com/bireme/Gestao-DeCS/issues/53#issuecomment-1894629967))
- Processamento no Ambiente Teste em Python3 do script “verifica_ORFAO.py” da pasta “/bases/decs.django/tools/tpl/” do Server OFI9

**Comment by acecampos** [comment]
@apendindan muito agradecemos!
Processo validado!

@lucianaPRB e @acecampos
