### ISSUE TITLE
Gerar base ISIS do FI-ADMIN Tesauro (DeCS 2024)

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/Gestao-DeCS#112]
Prezado Danilo, favor dar início ao processo de criação da base ISIS do DeCS edição de 2024. 

- [ ] Na pasta “/bases/dec.000/get_thesaurus/” mudar o nome do diretório “wrk_ths_1” para “wrk_ths_1_YYYYMMDD” 
- [ ] Criar um novo diretório chamado “wrk_ths_1” 
- [ ] Processamento em Shellscript do script “./harv_thesaurus.sh” na pasta “/bases/dec.000/get_thesaurus/tpl/”, com parâmetro “1” 

Agradecemos.

@acecampos psi

**Comment by apendindan** [comment]
Prezado @botturam 

A base ISIS do DeCS 2024 foi gerada e se encontra no path abaixo (serverofi9):
/bases/dec.000/get_thesaurus/wrk_ths_1/

Peço para que faça a validação da base para, caso validada, sigamos com as atividades.
