### ISSUE TITLE
Atualizar índice de pesquisa do Portal DeCS 2024

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/Gestao-DeCS#113]
Prezado Danilo,
favor dar início ao processo de atualização do índice de pesquisa do portal DeCS 2024.
Conforme Documentação: https://wiki.bireme.org/intranet/index.php/Indexacao_solr_tesauro_decs

@acecampos PSI

**Comment by lucianaPRB** [comment]
@viniciusandrade e @marcoslmori PSI

**Comment by apendindan** [comment]
Realizado o processamento do Índice Solr seguindo a documentação na Wiki
@lucianaPRB @acecampos por favor, validar, para vermos se já podemos dar continuidade no ambiente de produção

**Comment by acecampos** [comment]
@apendindan, fiz testes no decs teste (https://decs.teste.bvsalud.org) e não foi possível recuperar esses descritores:
https://decs.teste.bvsalud.org/ths?filter=ths_termall&q=Peroxidasina;
https://decs.teste.bvsalud.org/ths?filter=ths_termall&q=Ramucirumab;
https://decs.teste.bvsalud.org/ths?filter=ths_termall&q=Radi%C3%B4mica;
https://decs.teste.bvsalud.org/ths?filter=ths_termall&q=Articula%C3%A7%C3%A3o+Tibiofemoral;
https://decs.teste.bvsalud.org/ths?filter=ths_termall&q=Conflito+de+Pap%C3%A9is.
Obrigada.
@lucianaPRB, para ciência.

**Comment by apendindan** [comment]
O Wilson trouxe a hipótese de que o DeCS Teste tava linkado a Indice Solr de Produção, e não de Teste como imaginávamos de início. Assim, rodamos de novo para produção, e dando uma olhada rápida parecia ter atualizado mesmo, porém ficou com o problema de falta de decodificação utf-8 na árvore hierárquica, como segue em foto abaixo:
![imagem](https://github.com/bireme/Gestao-DeCS/assets/119962856/0997f2d5-023f-4f2f-8ab3-cf2a92ff9495)

Então, vimos que o problema estava no script em python chamado "cria_xml_solr.py" no diretório "/bases/dec.000/cria_indice_solr/tpl" que era rodado a partir do shellscript "leWeb_thesaurus.fnc". Estávamos rodando o programa em Python 3 e o script tinha sido feito em Python 2, e o problema vinha da falta de atualização do código. Após remover todos os ".enconding['ufr-8']" do código, rodamos de novo e o problema aparentou ser resolvido. 

Dito isso, gostaria de solicitar novamente a @lucianaPRB e @acecampos para que verifiquem, agora tanto o DeCS Produção quanto o DeCS Teste.

**Comment by lucianaPRB** [comment]
@apendindan Validado no ambiente de produção. Obrigada!
