### ISSUE TITLE
Atualizar cache do Portal DeCS 2024

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/Gestao-DeCS#114]
Prezado Danilo,
favor dar início ao processo de atualização do cache do portal DeCS 2024.

Documentação dos passos para atualização do cache do Portal DeCS
Executar os comandos abaixo no servidor de processamento:

```
$ cd /bases/dec.000/cria_cache/
$ ./Faz_LST.sh
$ # nohup ./Faz_cache_portal_DeCS.sh pt &> /bases/logs/celery/logs/CACHE_pt_YYYYYMMDD.log &
$ # nohup ./Faz_cache_portal_DeCS.sh es &> /bases/logs/celery/logs/CACHE_es_YYYYYMMDD.log &
```

Coordenar com @viniciusandrade e ITI

@marcoslmori para ciência

**Comment by viniciusandrade** [comment]
Oi @lucianaPRB e @apendindan, conforme conversamos o recomendado é iniciar o processo de atualização de cache em finais de semana/feriados devido a indisponibilidades nos sistemas que este processo pode ocasionar e também executar somente um idioma por vez.

Desta forma sugiro iniciar o processo na próxima sexta 17/05.

**Comment by apendindan** [comment]
Boa tarde

O processo de atualização do cache em português e em espanhol está finalizado. O número de páginas cujo HTML é de um tamanho próximo da página apenas com header é de 1250 para pt e 1250 para es, como ambas as línguas deram exatamente o mesmo número de páginas não carregadas, isso indica que são as páginas associadas a códigos DeCS desativados, e que, portanto, não eram para carregar mesmo.

Peço para a @acecampos e @lucianaPRB realizarem uma rápida verificação se as páginas que deveriam ter atualizações de fato estão atualizadas.

Abs,
Danilo

**Comment by acecampos** [comment]
Bom dia, @apendindan!
Processo validado; muitíssimo agradecida.
