### ISSUE TITLE
Fornecer token para a API do DeCS - UFPE

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#116]
Bom dia, @viniciusandrade!

Por favor, fornecer para Prof. Dr. Renato Correa Fernandes, da UFPE, sob licença LEG-2024-092, chave para API do DeCS.

Muito obrigada!

**Comment by viniciusandrade** [comment]
Bom dia @acecampos,

Token enviado por email. 

Abraços

**Comment by acecampos** [comment]
Obrigada, @viniciusandrade!
