### ISSUE TITLE
Geração dos Pacotes FTP com os arquivos de DeCS 2024 em XML para usuários licenciados

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/Gestao-DeCS#117]
Prezado @apendindan 
favor gerar os arquivos em xml do DeCS 2024 e disponibilizar no servidor FTP, de acordo com a [documentação](https://paho.sharepoint.com/sites/BIR/TC/TC/Forms/AllItems.aspx?id=%2Fsites%2FBIR%2FTC%2FTC%2FGerencias%2FDEV%2Fdocumentacao%2Dsaida%2Dfabio%2Dbrito%2FDeCS%2FFluxo%20de%20atualizacao%2F8%20%2D%20Criacao%20XML%20para%20FTP%20%2D%20Wilson%2DMarcelo%2FCriacao%20XML%20para%20FTP%2Etxt&parent=%2Fsites%2FBIR%2FTC%2FTC%2FGerencias%2FDEV%2Fdocumentacao%2Dsaida%2Dfabio%2Dbrito%2FDeCS%2FFluxo%20de%20atualizacao%2F8%20%2D%20Criacao%20XML%20para%20FTP%20%2D%20Wilson%2DMarcelo) disponível.

@acecampos será gerada nova senha de acesso para a edição 2024? Se sim, favor informar parâmetros ao Danilo via email.

@marcoslmori e @viniciusandrade para ciência.

**Comment by acecampos** [comment]
Obrigada, @lucianaPRB. Encaminhado email para informar parâmetros a @apendindan.

**Comment by apendindan** [comment]
Usuários e senhas dos FTPs que contém os arquivos estão nos emails da @acecampos e @lucianaPRB. Peço para que confirmem se ta tudo certo para acessar os FTPs e se os arquivos também estão corretos.

**Comment by acecampos** [comment]
@apendindan, agradeço! Consegui acessar o ftp e abrir o arquivo pt-br no Notepad ++.
Parece correto:
![image](https://github.com/bireme/Gestao-DeCS/assets/35345406/792b8f65-e5d3-4223-91d6-eadf7cb897f2)
