### ISSUE TITLE
Fornecer token para a API do DeCS - Hospital Israelita Albert Einstein

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#119]
@viniciusandrade, bom dia!

Por favor, forneça uma chave para a API do DeCS ao Hospital Israelita Albert Einstein, licenciado LEG ID-42905.
Agradeço!!

**Comment by viniciusandrade** [comment]
Bom dia @acecampos, 

Token enviado por email.

**Comment by acecampos** [comment]
Agradeço!
