### ISSUE TITLE
Fornecer token para a API do DeCS - Texto e Contexto Enfermagem

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#121]
Prezado @viniciusandrade,

Por favor, fornecer uma senha para a API do DeCS à licenciada Marinalda Boneli da Silva, sob licença BIR-28/24.

Grata!

**Comment by viniciusandrade** [comment]
@acecampos token enviado por email.

**Comment by acecampos** [comment]
Grata!
