### ISSUE TITLE
Mostrar a variante do espanhol da Espanha no portal do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#16]
@wilsonmoura e @marcioalvessilva já esboçaram um mock up funcional que foi aprovado.

**Comment by acecampos** [comment]
@wilsonmoura e @marcioalvessilva muito obrigada! Agora, a variante do espanhol da Espanha na interface em Português, Francês e Inglês já pode ser visualizada. Mas na interface do espanhol não está visível. Imagino que seja alguma impossibilidade do próprio campo, já que os dois são do idioma espanhol. Vamos marcar para falar sobre isso?

Solicito que seja corrigido de "spanish form Spain" para "**Spanish from Spain**", com letra maiúscula para o idioma e país. No inglês, é uma regra bem rigorosa escrever o idioma com letra maiúscula.

Se possível, também escrever esse botão nos outros idiomas:
                PORTUGUÊS => Espanhol da Espanha
                ESPANHOL => Español de España
                FRANCÊS => Espagnol d'Espagne
                INGLÊS => Spanish from Spain
Se não for possível, deixar só no inglês corrigido, por favor.

@lucianaPRB para seu acompanhamento também

**Comment by wilsonmoura** [comment]
@acecampos o texto foi atualizado conforme solicitado. Favor validar no ambiente de testes.

**Comment by acecampos** [comment]
@wilsonmoura ficou perfeito. Validado. Grata!
