### ISSUE TITLE
Carregamento das notas de escopo (alteradas + novas 2022)

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#20]
@wilsonmoura Bom dia! 
A @lucianaPRB terminou as notas de escopo e agrupou os idiomas todos em uma só lista. Agrupei as notas alteradas e as novas em um só arquivo, imaginando que possa ser mais prático para você, pois o script substitui o conteúdo do campo pelo que estiver na coluna ScopeNote.
Por favor, carregue no Fi-Admin as notas de escopo do arquivo anexo.
Muito obrigada!
[ScopeNote-new+changed-ENG-ES-(ES-ES)-POR.xlsx](https://github.com/bireme/Gestao-DeCS/files/8105475/ScopeNote-new%2Bchanged-ENG-ES-.ES-ES.-POR.xlsx)
!

**Comment by wilsonmoura** [comment]
@acecampos notas de escopo atualizadas no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura Obrigada. Validado no ambiente de produção.
