### ISSUE TITLE
DescriptorUI (DUI) não encontrado nos novos

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#22]
Ao iniciarmos a inserção dos novos no FI-Admin, não encontramos os seguintes DUI, todos de termos que já existiam no DeCS em outros registros e como conceitos não preferidos:

D000087302 => MH: Bias, Implicit
D000088302 => MH: HIV Non-Progressors
D000088642 => MH: Nonagenarians
D000089783 => MH: Defective Interfering Viruses => carregou todos, mas não criou o Conceito preferido, e assim, não podemos mudar nada pelo Fi-Admin. Tentei criar o conceito preferido para depois mudar o código hierárquico, mas não consegui.
Os termos estavam no status "Histórico" porque assim os gravei imaginando que seria mais fácil para migrar. Em outros exemplos, o procedimento carregou, sim, termos que estavam no histórico. E eles ficaram duplicados como "Publicado" e como "Histórico". Ex.: Escitalopram.

Obs: nenhum desses apareceu nos relatórios da primeira fase.

Acho que teria que criar os DUI por baixo, menos no caso do D000089783, que aparece no registro, mas como naõ tem o coneito preferido, ele não aparece na busca.

**Comment by acecampos** [comment]
Atualização do que fizemos juntos por chamada no Teams

Favor trocar os DescriptorUI:

- DDCS059938 por D000087302 => MH: Bias, Implicit.
Nesse registro, não está sendo possível inserir os códigos hierárquicos do MeSH como devem no ambiente de produção. Aparece mensagem de que o código hierárquico já existe, porém, ao fazer a busca com o código hierárquico, não recupera nada.

- D000088302 => MH: HIV Non-Progressors (não consegui criar no ambiente de produção, mas deu certo no de testes)
- D000088642 => MH: Nonagenarians (não consegui criar no ambiente de produção, mas deu certo no de testes)
-Apareceu a mensagem abaixo:
![image](https://user-images.githubusercontent.com/35345406/155819635-a3ed9e03-2c8f-4c20-906b-8dda22d16d41.png)

- Resolvido (Y) no campo de conceito preferido D000089783 no ambiente de teste => Defective Interfering Viruses => registro estava sem conceito preferido

**Comment by wilsonmoura** [comment]
Ajustes realizados, com acompanhamento da solicitante, aplicando as consultas abaixo:

- Código Hierárquico
```
SELECT * FROM thesaurus_treenumberslistdesc WHERE tree_number='???.???.???.???.???'
DELETE FROM thesaurus_treenumberslistdesc WHERE id=?????
```
- ID de Transporte:
```
SELECT * FROM thesaurus_identifierdesc WHERE descriptor_ui='??????????'
UPDATE thesaurus_identifierdesc SET descriptor_ui='??????????' WHERE id=?????
```

**Comment by acecampos** [comment]
@wilsonmoura obrigada! Validado!
