### ISSUE TITLE
Carregamento das notas de indexação (annotation) alteradas do inglês

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#23]
Oi, @wilsonmoura! Por favor, carregar as notas de indexação annotation que vieram alteradas da NLM, conforme arquivo
[annotation_changes.txt](https://github.com/bireme/Gestao-DeCS/files/8141464/annotation_changes.txt)
 .
A @lucianaPRB  **já** inseriu manualmente as de **es** e **pt-br** alteradas.
Agradecida!

**Comment by wilsonmoura** [comment]
@acecampos notas de indexação atualizadas no ambiente de testes. Favor validar.

Segue também relatório das notas que estavam vazias. Nesse caso, devem ser removidas manualmente via FI-ADMIN.

[Annotation_VAZIO.txt](https://github.com/bireme/Gestao-DeCS/files/8236881/Annotation_VAZIO.txt)

**Comment by acecampos** [comment]
D000073566 vazio mesmo;
D001300 vazio mesmo;
D001766 vazio mesmo;
D003673 vazio mesmo;
D006320 vazio mesmo.

Ok, @wilsonmoura Validado; obrigada!
