### ISSUE TITLE
Erro ao transportar termos para os conceitos já existentes em registros novos

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#28]
Conforme apresentado em reunião via Teams, @wilsonmoura estariam os MUI duplicados?

- DUI: D000091123; MUI: M000747897
- DUI: D000090262; MUI: M000745885

**Comment by acecampos** [comment]
DUI: D000090262; MUI: M000745885 => conseguimos resolver modificando o termo no conceito, deixando-o errado e colocando o termo correto no conceito M000745885.

**Comment by wilsonmoura** [comment]
Resolvido em bireme/fi-admin#1307
