### ISSUE TITLE
IDs de transporte duplicados com diferentes ID de tesauro

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#29]
@wilsonmoura, conforme apresentado em reunião via Teams, os seguintes DUI estão duplicados e não conseguem ser recuperados no FI-Admin. Recuperamos seus registros somente pelas _strings_. Quando me refiro a mfn=ID do tesauro.

D000088302 => MH: HIV Non-Progressors: mfn=59675 e mfn=59942 
D000089783 => MH: Defective Interfering Viruses mfn=59736 e mfn=59944
D000087302 => MH: Bias, Implicit: mfn=59630 e mfn=59938
D000088642 => MH: Nonagenarians: mfn=59943 e mfn=59691 (**incerto**)

Com relação aos registros acima, os que tem mfn de maior valor são os que já estão atualizados quanto ao código hierárquico (problema apresentado no issue #22).

Obs.: D000088642=> MH: Nonagenarians: não recuperamos pelo DUI, mas desconheço se há duplicação de DUI. Não consegui achar outro mfn associado a esse DUI, mas é provável que seja 59691 porque não recupera nada e vem na sequência de carregamento automático dos novos. Fiz a bobagem de entrar um termo alternativo no registro do mfn=59943, que poderia ser a chave para achar o outro mfn.

**Comment by acecampos** [comment]
Ação validada:

No ambiente de **TESTE**, foram recuperados pelo DescriptorUI, e completados com as traduções aos 3 idiomas, os registros:
D000088302 => MH: HIV Non-Progressors: mfn=59942
D000089783 => MH: Defective Interfering Viruses: mfn=59944
D000087302 => MH: Bias, Implicit: mfn=59938
D000088642 => MH: Nonagenarians: mfn=59943

@wilsonmoura por favor, pode replicar o ambiente de teste para o ambiente de trabalho, conforme conversado por Teams?

**Comment by wilsonmoura** [comment]
Resolvido em bireme/fi-admin#1313
