### ISSUE TITLE
Erro na recuperação por ID do tesauro

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#30]
![image](https://user-images.githubusercontent.com/35345406/162336894-75a35d0e-bb81-4087-b84a-f7f5bd374978.png)

A imagem acima foi obtida pela busca pelos mfn=59600 e mfn=59601

![image](https://user-images.githubusercontent.com/35345406/162336973-aea909a3-bd7d-4f7e-b6dd-01deb5c1a4c8.png)

É possível que neles estejam alguma duplicação de DUI??

**Comment by wilsonmoura** [comment]
Resolvido em bireme/fi-admin#1308
