### ISSUE TITLE
ConceptUI M0027777: PEP pt-br apagado 

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#34]
@wilsonmoura,
O campo pt-br do PEP de ConceptUI M0027777 - Alimentação por Mamadeira - foi erroneamente apagado antes de tirá-lo como preferido, apresentando o seguinte status:
ID do termo: pord067919
Termo preferido do conceito: **Y**
Termo preferido do registro: N
Ao apagar um termo preferido, o campo não consegue ser substituído. Por isso, se for possível, solicito a remoção manual desse registro apagado, a fim de liberar o campo para o termo correto.
Grata!

**Comment by acecampos** [comment]
@wilsonmoura resolvido! Obrigada!

**Comment by acecampos** [comment]
Resolvido via área administrativa do Fi-Admin. Grata!

**Comment by acecampos** [comment]
@wilsonmoura apareceu um outro caso igual com a lista que a NLM nos mandou:
ConceptUI: M000738864
idioma **pt-br**
string errado: Brodmann Area 3

Solicito a remoção manual desse registro apagado, a fim de liberar o campo para o termo correto.
Grata

**Comment by wilsonmoura** [comment]
@acecampos resolvido via área administrativa do FI-ADMIN (tabela `termlistdesc`).
