### ISSUE TITLE
Adequar a apresentação das categorias no iAHx à codificação do DeCS/MeSH

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#38]
Problema: A hierarquia apresentada no iAHx está hoje representada por números, ao invés das letras que representam as categorias.
Exemplo:

![image](https://user-images.githubusercontent.com/35345406/188131731-aebc614c-a15c-4c52-8c03-49d85c6f1adc.png)

No exemplo acima, o correto seria apresentar: **A. Anatomia**, pois "A" é o código hierárquico que identifica a categoria Anatomia do DeCS/MeSH.
Por favor, aplicar em toda a estrutura os códigos corretos.

Grata

(@lucianaPRB, para seu conhecimento)

**Comment by viniciusandrade** [comment]
@acecampos ajuste realizado retirando a numeração e adicionado o código hierárquico para a o primeiro nível da árvore.

![image](https://user-images.githubusercontent.com/349287/190260659-cf3719f4-6a85-41e7-a9d2-a86903333f29.png)

Poderia verificar se agora esta OK?

Obrigado

**Comment by acecampos** [comment]
@viniciusandrade está ótimo! Muito obrigada!
