### ISSUE TITLE
Tradução novos2023 em conceitos existentes e notas de indexação alteradas

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#41]
Por favor, peço que faça a tradução

1. dos novos termos em registros já existentes (filtrado por categoria)
2. das notas de indexação alteradas

Planilhas no Sharepoint.
Peço que faça uma amostra e estime o tempo empregado na tradução do todo, ok?

**Comment by lucianaPRB** [comment]
@acecampos Quais as categorias específicas?

**Comment by acecampos** [comment]
@Rio Branco, Luciana ***@***.***>
CAT. B, G, H, I, J, K, L, M, N, Z

Ana Cristina Espindola Campos

Terminologias e Classificações em Saúde

BIREME<https://www.paho.org/bireme/index.php?lang=pt> | OPAS | OMS

 [cid:8a08a13f-d955-4b8d-bba9-fd1fbdbe7495]

________________________________
De: lucianaPRB ***@***.***>
Enviado: segunda-feira, 10 de outubro de 2022 17:42
Para: bireme/Gestao-DeCS ***@***.***>
Cc: Campos, Ana Cristina Espindola (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/Gestao-DeCS] Tradução novos2023 em conceitos existentes e notas de indexação alteradas (Issue #41)


@acecampos<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facecampos&data=05%7C01%7Ccamposan%40paho.org%7C9ce6bba291404d5c067708daaaffecfd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638010313454951044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z5nLmVGK%2FVGc9V5SwAKApHQ6aDTRfW3Vu7KEx6dvgY4%3D&reserved=0> Quais as categorias específicas?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2FGestao-DeCS%2Fissues%2F41%23issuecomment-1273801168&data=05%7C01%7Ccamposan%40paho.org%7C9ce6bba291404d5c067708daaaffecfd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638010313454951044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eY8gZDElYf50lY1AceCbc0mnbOV9Y6zqDXJceFRx4zI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINVH7QKYP7HBJJ7FJGRRZDWCR5SVANCNFSM6AAAAAAQMMIZU4&data=05%7C01%7Ccamposan%40paho.org%7C9ce6bba291404d5c067708daaaffecfd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638010313455107253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5ASMuY0AJ8YY4jZLWP1xE0Ofka%2BpzTV4QpPjWc8UFwE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
