### ISSUE TITLE
Carregar o MeSH 2023 no Fi-Admin/thesaurus

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#43]
@wilsonmoura por favor, carregar o MeSH2023 de acordo com o email enviado por mim em 23set22.
Grata!

@lucianaPRB, para seu conhecimento.

**Comment by acecampos** [comment]
@wilsonmoura Validado o carregamento no ambiente de testes dos new_2023.
Aguardando:

- carregamento de changed_marked no ambiente de teste
- relatórios gerados em decorrência dos carregamentos

**Comment by wilsonmoura** [comment]
@acecampos finalizamos o carregamento dos novos descritores e descritores alterados no ambiente de testes do [FI-ADMIN](https://fi-admin.teste.bvsalud.org).

Segue arquivo ZIP com os relatórios para análise gerados após o carregamento: [decs_reports.zip](https://github.com/bireme/Gestao-DeCS/files/9670888/decs_reports.zip)

OBS: Favor desconsiderar os arquivos que estão vazios.

**Comment by acecampos** [comment]
@wilsonmoura, validado o carregamento dos termos novos e alterados no ambiente de testes. Fiz ajustes que ainda eram necessários no sistema Fi-Admin de edição para minimizar ainda mais o conteúdo dos próximos relatórios. Agradeço se puder carregar os novos e alterados no ambiente de produção.

**Comment by wilsonmoura** [comment]
@acecampos para atualizar o ambiente de produção, será necessário refazer o carregamento no ambiente de testes e realizar nova validação. Após isso, faremos a transferência para ambiente de produção. Vale ressaltar que devemos paralisar a entrada/edição de dados no ambiente de produção até finalizarmos todo o processo de carregamento e validação dos termos novos/alterados para enfim realizarmos a atualização do ambiente de produção. Sendo assim, favor informar o momento mais adequado para a paralisação do ambiente de produção para darmos início ao carregamento.

**Comment by acecampos** [comment]
@wilsonmoura Informo que o ambiente de produção já pode ser paralizado para dar início ao carregamento. Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos finalizamos novamente o carregamento dos novos descritores e descritores alterados no ambiente de testes do [FI-ADMIN](https://fi-admin.teste.bvsalud.org).

Segue arquivo ZIP com os relatórios para análise gerados após o carregamento: [decs_reports.zip](https://github.com/bireme/Gestao-DeCS/files/9701896/decs_reports.zip)

OBS: Favor desconsiderar os arquivos que estão vazios.

**Comment by acecampos** [comment]
@wilsonmoura Obrigada pelo carregamento.
O D000093845 parece estar corrompido no [FI-ADMIN](https://fi-admin.teste.bvsalud.org/).
Ou foi deletado por algum motivo. Não é possível encontrar esse DUI.
No restante, está validado.

**Comment by wilsonmoura** [comment]
@acecampos o DUI D000093845 refere-se ao novo termo "Sophora flavescens". Por algum motivo, esse registro não foi inserido no processamento responsável pelo carregamento. Nesse caso, como devemos proceder? Deve ser inserido manualmente?

**Comment by acecampos** [comment]
Oi, @wilsonmoura sim. O estranho é que os dois descritores mais específicos de Sophora ficaram de fora: 
Sophora ﬂavescens [B01.875.800.575.912.250.401.734.500] e 
Sophora japonica [B01.875.800.575.912.250.401.734.750]

Sophora [B01.875.800.575.912.250.401.734] ](https://meshb-prev.nlm.nih.gov/record/ui?ui=D029909)
[Sophora ﬂavescens [B01.875.800.575.912.250.401.734.500]](https://meshb-prev.nlm.nih.gov/record/ui?ui=D000093845)
[Sophora japonica [B01.875.800.575.912.250.401.734.750]](https://meshb-prev.nlm.nih.gov/record/ui?ui=D000093846)

**Comment by acecampos** [comment]
@wilsonmoura 
Inserido manualmente no ambiente de testes com o ID de transporte DDCS060342. Por favor, mudá-lo para D000093845. Grata

**Comment by wilsonmoura** [comment]
@acecampos ambiente de produção atualizado e liberado para uso.

**Comment by acecampos** [comment]
Obrigada, @wilsonmoura!
