### ISSUE TITLE
Corrigir violações de regras encontradas pela NLM

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#45]
Relação de DUIs com violações: 
e-mail "Follow-up - missing PEPs" from Stephanie Lippow to Ana Cristina Campos em 01set22.

**Comment by lucianaPRB** [comment]
Tema já incluído no issue [https://github.com/bireme/Gestao-DeCS/issues/39](url)

**Comment by wilsonmoura** [comment]
@lucianaPRB Dica: para mencionar issues que estão dentro do mesmo repositório, basta digitar # junto com o ID do respectivo issue. Por exemplo: #39

**Comment by lucianaPRB** [comment]
Entendi @wilsonmoura! Obrigada pela dica (:
