### ISSUE TITLE
Desabilitar a publicação de registros sem termos preferidos com status Publicado

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#48]
Relacionado com #47

**Comment by wilsonmoura** [comment]
@acecampos resolvido em bireme/thesaurus-wp-plugin#102. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura, o resultado por termo exato deu certo, isto é, não apareceu na busca. 
Porém, o resultado continua aparecendo por qualquer termo da expressão do descritor. Exemplo:
Busca por "Trabalho" em "Qualquer termo" aparece o registro em que o termo "Telerregulação do Trabalho da Telessaúde" está sem descritor (MH).
Visualizando na figura abaixo:

![image](https://user-images.githubusercontent.com/35345406/200386217-ea63b941-f3ff-428c-a723-2705b0788ed6.png)

**Comment by wilsonmoura** [comment]
@acecampos fizemos mais alguns ajustes. Favor validar novamente no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Obrigada!
