### ISSUE TITLE
Ação Farmacológica traduzir

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#49]

**Comment by acecampos** [comment]
@wilsonmoura Analisamos novamente e vimos que o relacionamento já existe e é só uma questão de apresentar o termo nos diferentes idiomas.

**Comment by wilsonmoura** [comment]
bireme/fi-admin#462

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura, validado. Muito obrigada! 
Não terminei de apagar as traduções dos que havia inserido manualmente (no ambiente de produção). Devo terminar antes de você transpor para o ambiente de produção?

**Comment by wilsonmoura** [comment]
@acecampos com exceção no idioma inglês (idioma obrigatório), as traduções inseridas não estão mais sendo consideradas. Sendo assim, podemos sim atualizar o ambiente de produção sem essa dependência de remoção das traduções. Vale ressaltar que esses ajustes só serão refletidos no ambiente de produção no próximo lançamento do DeCS, pois será necessário atualização do cache do portal.

**Comment by acecampos** [comment]
Ok, Wilson, obrigada!
