### ISSUE TITLE
Testes nova API DeCS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/Gestao-DeCS#50]
Documentação do serviço atual (v1)

http://wiki.reddes.bvsalud.org/index.php/Servi%C3%A7os_DeCS

URLs para testes da versão atual (v1) com a versão nova (v2):

https://api.teste.bvsalud.org/decs/v1/get-tree/
https://api.teste.bvsalud.org/decs/v2/get-tree/

https://api.teste.bvsalud.org/decs/v1/search-by-words/
https://api.teste.bvsalud.org/decs/v2/search-by-words/ 

https://api.teste.bvsalud.org/decs/v1/search-by-boolean/
https://api.teste.bvsalud.org/decs/v2/search-by-boolean/

**Comment by viniciusandrade** [comment]
Meninas,

A desenvolvedora da INFOMED realizou novos ajustes na API e identificou os resultados adicionais que a Ana tinha identificado nos testes iniciais que eram termos históricos.

Eu ajustei as chamadas lá no Postman para utilizar esta nova versão e também agreguei para cada chamada na aba "Headers" a informação da apikey que agora precisa ser passada para liberar o uso da API.

Agradeço se puderem realizar novos testes para identifcar problemas comparando as versões (v1) e (v2) da API.

Obrigado.

**Comment by viniciusandrade** [comment]
@lucianaPRB fiz a atualização do serviço de localização de descritores da pesquisa em ambiente de testes e notei que ao clicar em um nó de primeiro nível o serviço da versão 2 provavelmente não esta trazendo os mesmos dados da versão 1. 
Exemplo:
https://pesquisa.teste.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=HP

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=HP

Favor comparar o retorno em XML das duas versões usando o método **get-tree** e informar o que esta faltando para que possa pedir para a desenvolvedora do INFOMED dar uma olhada.

Obrigado

**Comment by lucianaPRB** [comment]
@viniciusandrade É preciso fazer a atualização referente ao [issue](https://github.com/bireme/iahx-opac/issues/331)

Obrigada!

**Comment by viniciusandrade** [comment]
@lucianaPRB ajuste realizado para v2 da API, quando possível favor validar usando o ambiente de testes da pesquisa.

**Comment by viniciusandrade** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/349287/231534865-b41ba098-f740-4a6a-af59-96f14205e4ad.png)
@lucianaPRB ajuste realizado na v2 da API, quando possível favor validar usando o ambiente de testes da pesquisa.

**Comment by viniciusandrade** [comment]
Correção aplicada na estrutura do XML da API v2:
- Alterado nome do elemento ```<descendant>``` para ```<descendants>``` para compatiblidade com v1 da API.

Ajuste também realizado no IAHx para mostrar corretamente a estrutura da categoria HP1:

https://pesquisa.teste.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=HP1

**Comment by lucianaPRB** [comment]
@viniciusandrade Confirmadas as alterações nos nomes das Categorias VS e SH.
Obrigada!

**Comment by lucianaPRB** [comment]
@viniciusandrade Verificar a possibilidade de inclusão do descritor no idioma francês também no canto superior direito junto com os demais idiomas, cf. imagem:

![image](https://user-images.githubusercontent.com/93340661/231545383-0a3f18e8-32a6-4d3f-b24a-9df9d329995f.png)

**Comment by viniciusandrade** [comment]
@lucianaPRB ajustes realizados pela desenvolvedora e disponíveis no ambiente de teste para validação. 

Pelo que pude verificar parece que foi aplicado correção para as categoras H,V,M. Por favor, da uma olhada se o problema ocorre também para outras categorias.

Obrigado

**Comment by viniciusandrade** [comment]
Finalizado pois a validação foi concluída.
