### ISSUE TITLE
Preparar arquivos MSHPOR e MSHSPA para enviar à NLM

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#53]
@wilsonmoura, peço a gentileza de elaborar os arquivos MSHPOR e MSHSPA para envio à NLM. 
São aqueles arquivos txt tabulados, conforme feito no ano passado. Estamos à disposição para esclarecer dúvidas referentes ao processo. Muito obrigada!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos segue arquivo compactado com os documentos solicitados: [RELATORIOS_TERMOS_BIREME.zip](https://github.com/bireme/Gestao-DeCS/files/10686085/RELATORIOS_TERMOS_BIREME.zip)

**Comment by acecampos** [comment]
@wilsonmoura Obrigada!! Ficaram ótimos. Fiz um ajuste de espaço duplo em 1 termo em português e 2 em espanhol, além de um ET que estava marcando MH - erro meu. Consertei no txt e vou enviar para a NLM. Validado!

**Comment by wilsonmoura** [comment]
Documentação: [Sharepoint](https://paho.sharepoint.com/:t:/r/sites/BIR/TC/TC/Gerencias/DEV/documentacao-saida-fabio-brito/DeCS/Fluxo%20de%20atualizacao/7%20-%20Criacao%20relatorio%20para%20NLM%20-%20Wilson/Criacao%20relatorio%20para%20NLM.txt?csf=1&web=1&e=KZBDd3)

**Comment by botturam** [comment]
para atualizar o ambiente de teste:

bases/decs.django/bkp_mysql $ ./loaddata_crontab_backup_mysql_thesaurus_TABLES_SERVIDOR_PROD.sh

a execução trará instruções extras para seguimento
