### ISSUE TITLE
Recuperar os metadados do MeSH-FRE2022

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#55]
@wilsonmoura, favor usar o pacote de 2022 já testado e validado em Fi-Admin-teste.
Estimativa de tempo: 4 dias para completar o carregamento.
item 1.1 do issue db-processing #885

**Comment by wilsonmoura** [comment]
@acecampos carregamento do MSHFRE finalizado. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
- Método de checagem do carregamento: comparação Fi-Admin produção x Fi-Admin testes por amostragem.
- Amostra de registros envolveu descritores MH, PEPs e ETs.
- Amostra:

Stress Granules
Vestibular System
Afrotheria => conceitos não preferidos OK
Axial Spondyloarthritis
Diaschisisa => conceitos não preferidos OK
Livedoid Vasculopathy => ETs OK
Mast Cell Activation Disorders => conceitos não preferidos OK
Body Odor
MINOCA
Erythema Ab Igne
Tripeptidyl-Peptidase 1 => ETs OK
Endoplasmic Reticulum Chaperone BiP
Ribosomal Protein L3
Filaggrin Proteins
Protocadherins => ETs OK
Mirror Movement Therapy
Self-Compassion
Geroscience
Climate Models
Birth Cohort
Biosecurity

@wilsonmoura, Validado no ambiente de testes.
Muito obrigada.

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/thesaurus-wp-plugin/issues/81
