### ISSUE TITLE
Eliminar termo YY status Apagado pelo MySQL 

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#59]
@wilsonmoura poderia, por favor, eliminar o registro Paramedics no es-es que está apagado, mas consta como YY e, por isso, não conseguimos entrar o termo correto?
DIU: D000094783
CUI: M0000734
lang: (es-es)
Paramedics status Apagado
termo preferido do conceito: Y 
termo preferido do registro: Y
![image](https://user-images.githubusercontent.com/35345406/217665109-eef651be-7fc2-4dd8-95ec-70a7154e8a5f.png)

Obrigada!

@acecampos e @lucianaPRB

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
Validado. Obrigada, @wilson!
