### ISSUE TITLE
Inserir os novos automaticamente

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#6]
planilha changed_marked POR
planilha changed_marked SPA

**Comment by acecampos** [comment]
@wilsonmoura por favor, carregar os novos termos do MeSH 2022 conforme e-mail encaminhado a você em 20jan22 com os arquivos **new_mh-2022.txt** e **changed_marked-POR-2022.xlsx**. Estou seguindo as orientações do Arthur em

![image](https://user-images.githubusercontent.com/35345406/150408586-5d86887e-2c21-47cc-a63e-7c57ea9cc57d.png)

Já deixei aclguns conceitos manualmente em status histórico, mas aparentemente isso não afeta em nada a migração automática dos conceitos. pois, quando migram de DescriptorUI, eles são alterados para o status Publicado.

Espanha enviou changed_marked-SPA-SPA em 18jan22 e o Chile enviou changed_marked-SPA-CHI, em 20jan22. Ainda estou fazendo uma revisão por amostragem desses arquivos.

Muito obrigada!

**Comment by acecampos** [comment]
@wilsonmoura por favor, desconsidere por enquanto esse comentário.

**Comment by acecampos** [comment]
@wilsonmoura favor carregar o arquivo new_mh-2022.txt. Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos creio que enfim conseguimos finalizar o carregamento dos novos descritores no ambiente de testes do [FI-ADMIN](https://fi-admin.teste.bvsalud.org) sem erros no processamento.

De acordo com a documentação feita pelo Fabinho, estou enviando os relatórios abaixo para análise:

- [step1_b_TERMOS_NOVOS__JA_EXISTEM_VERIFICAR.txt](https://github.com/bireme/Gestao-DeCS/files/7973962/step1_b_TERMOS_NOVOS__JA_EXISTEM_VERIFICAR.txt)
- [CHANGED_MARKED__step1_a_VERIFICAR_SE_POSICIONAMENTO_PROCEDE.txt](https://github.com/bireme/Gestao-DeCS/files/7973985/CHANGED_MARKED__step1_a_VERIFICAR_SE_POSICIONAMENTO_PROCEDE.txt)
- [NEW_ROW_JA_EXISTE_avaliar.txt](https://github.com/bireme/Gestao-DeCS/files/7973977/NEW_ROW_JA_EXISTE_avaliar.txt)
- [step_atualiza_tree_number_XML_x_Tesauro.txt](https://github.com/bireme/Gestao-DeCS/files/7973988/step_atualiza_tree_number_XML_x_Tesauro.txt)

**Comment by acecampos** [comment]
@wilsonmoura agradeço muito. Vou analisar os relatórios cuidadosamente.

**Comment by acecampos** [comment]
@wilsonmoura o último relatório indicou dois registros sem DescriptorUI (= ID de transporte). Por favor, colocar por baixo do sistema, pois os respectivos campos estão bloqueados para edição no Fi-Admin.
São eles:
String: Citizenship => ID de transporte D000087482
Sring: Livedoid Vasculopethy => ID de transporte D000090122

Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados conforme solicitado. Favor validar no ambiente de testes. Fico no aguardo do OK para replicar a base do ambiente de testes para a base de trabalho.

**Comment by acecampos** [comment]
@wilsonmoura ok, validado. grata!

**Comment by wilsonmoura** [comment]
@acecampos ambiente de trabalho atualizado. Favor validar.

**Comment by wilsonmoura** [comment]
@acecampos ambiente de trabalho atualizado e liberado para uso. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Grata!
