### ISSUE TITLE
Preparo das páginas no Wordpress da nova edição

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/Gestao-DeCS#63]
Lu => páginas com os gráficos
Márcio => converter as páginas para edição atual as adaptações das páginas anteriores e ajuste nas tabelas coladas.

**Comment by acecampos** [comment]
Luciana, para informe, abri o https://github.com/bireme/wordpress-themes/issues/167#issue-1626227730
para a confecção da página de quantidades atualizadas de 2023.

**Comment by acecampos** [comment]
@lucianaPRB, carreguei as imagens feitas pelo @marcioalvessilva no WordPress do portal DeCS/MeSH, ok?
