### ISSUE TITLE
Fornecer token para a API do DeCS - UNDAC

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#85]
Bom dia!
Por favor, fornecer chave API para Alan Miguel Carlos Silvestre, desarrollador de la Universidad Nacional Daniel Alcides, que possui licença para acesso aos dados do DeCS #LEG-2023-0134.
Obrigada!

**Comment by viniciusandrade** [comment]
Token enviado por email. Favor verificar. Obrigado.

**Comment by acecampos** [comment]
Muito obrigada!
