### ISSUE TITLE
Fornecer token para a API do DeCS - SE-UNA/SUS

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#86]
Boa tarde!

Por favor, fornecer chave API para Maria Fabiana Damásio Passos, da Secretaria Executiva da Universidade Aberta do SUS, SE-UNA/SUS, que possui licença para acesso aos dados do DeCS #LEG-2023-0136.

@viniciusandrade, tenho em minhas anotações que esse Licenciado deverá/poderá testar a API.

Obrigada!

**Comment by viniciusandrade** [comment]
Token enviado por email. Favor verificar. Obrigado.

**Comment by acecampos** [comment]
Recebido. Obrigada!
