### ISSUE TITLE
Fornecer token para a API do DeCS - UNICAMP

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#87]
Bom dia!

Por favor, fornecer chave API para Márcia Jacobina Andrade da Silva Martins, doutoranda da UNICAMP, que possui licença para acesso aos dados do DeCS #LEG-2023-0154.

Obrigada!

**Comment by viniciusandrade** [comment]
Bom dia Ana,
Chave enviada para seu email.

Abraços
