### ISSUE TITLE
Acessar DeCS 2023 via ftp

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#88]
@wilsonmoura, Presente de aniversário: um issue no git. ; )
Há usuário DeCS relatando que os dados para acesso ao ftp remetem para os arquivos de 2022.

O login e a senha de acesso do usuário que forneci foram os que você mandou em um e-mail de 09mai23.

Mas ele recuperou isso:
![image](https://github.com/bireme/Gestao-DeCS/assets/35345406/0d825142-7e60-4cff-90cf-ad4f9a5e6745)

Eu também recuperei o pacote de 2022 quando fiz o caminho que orientei o usuário a fazer.
Entretanto, quando entrei como usuário BIREME, consegui acessar o pacote de 2023.
Então, peço a você que verifique se há algum problema.
(Minha suspeita é desc ao invés de decs)

Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos normalizamos o acesso aos arquivos disponíveis no servidor FTP. Favor validar.

**Comment by acecampos** [comment]
Oi, Wilson! Validado, muito obrigada!
Continuo com uma dúvida: entrei como usuário decs_es não foi pedida a senha. Será porque eu já tinha acesso por aqui com usuário Bireme?

**Comment by acecampos** [comment]
Obrigada, Wilson!
