### ISSUE TITLE
Acesso ao Fi-Admin/thesaurus

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#89]
Bom dia, Wilson!
A Katinha, por meu pedido, criou uma conta para o coordenador do comitê de Homeopatia. Só que não está funcionando. Não tem nenhuma opção.

![image](https://github.com/bireme/Gestao-DeCS/assets/35345406/c4d9285d-d78c-4f82-bd93-dbe209227cc7)

Queríamos também que fosse uma conta que tivesse restrição para editar e fosse só para visualização. Você poderia verificar o que está ocorrendo, por favor?

Centro Cooperante: BR.926
Login de usuário: alvaro.mesquita
Senha criada: te passo por e-mail.

Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Obrigada, Wilson!
Validado.
