### ISSUE TITLE
Deixar a data da última atualização do descritor no site público

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#9]
Por meio de mensagem de usuário, notamos a necessidade de colocar a data de revisão do descritor. Muitos descritores de SP vão ser alterados em 2022 e talvez precisemos deixar claro nos registros deles.
![image](https://user-images.githubusercontent.com/35345406/145445199-3b072fc1-82d3-4d52-b24c-762a47954a9a.png)

**Comment by acecampos** [comment]
@wilsonmoura Observação: considerar a data de qualquer alteração no registro: como campo de descritor, sinônimo, nota de escopo, nota de indexação, de termo relacionado, ou qualificador permitido.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura ótima solução para o Fi-Admin. Obrigada! 
Entretanto, só consegui ver no ambiente de produção. O Fi-Admin de teste apareceu assim:
![image](https://user-images.githubusercontent.com/35345406/184415844-88f31bfc-72f4-499e-9c10-72508744f517.png)

Dúvidas:
- não compreendi o significado dos valores realçados na figura abaixo, apesar de saber o que foi feito, pois removi as notas de indexação em en, es e pt-br hoje mesmo:
                 ![image](https://user-images.githubusercontent.com/35345406/184415397-04d6226f-3a85-4d88-a13d-a8f44d8a4b4c.png)
    são códigos do tipo de alteração feita no campo ou não devem ser considerados por serem gerados a cada salvamento?
- vai ser possível mostrar a data da alteração **mais recente** para a página pública por essa solução apresentada?
- criei um novo sinônimo no registro de DUI DDCS060062 como teste e esse tipo de ação não constou no pop-up de histórico de mudanças criado. Quais tipos de alterações que vão aparecer nele? Já vimos que o recurso mostra a remoção da nota de indexação nos idiomas em que mexi e também que, em outro registro, aparece **novo** com data e usuário que fez a criação/alteração de descritor, mas não apareceu novo para criação/alteração de termo alternativo.
                                 Descrição: → None
                                 Categoria Hierárquica De Descritor: → None
                                 Categoria Hierárquica De Descritor: → None
                                 Lista De Ação Farmacológica: → None
                                 Indexação Prévia: → None
                    ![image](https://user-images.githubusercontent.com/35345406/184425254-c5970cd1-759d-4cee-bdb6-cf4e05d862dd.png)

Vamos nos falar pelo Teams na próxima semana para sanar essas dúvidas?
Grata!

**Comment by acecampos** [comment]
@wilsonmoura validada a data de última atualização no registro. Falta ajuste no Histórico, conforme conversa pelo Teams.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados.
