### ISSUE TITLE
Atribuir acesso ao Fi-Admin/thesaurus 

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#90]
Oi, Wilson!
Por favor, poderia atribuir acesso ao Fi-Admin/thesaurus para o usuário **Leonardo Ragacini** pelo BR926.1 como documentalista e editor? Ele já tem acesso às fontes referenciais.

Obrigada !

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado. Obrigada!!
