### ISSUE TITLE
Padronizar idiomas de descritores no iAHx

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#91]
@viniciusandrade, Boa tarde!
Espero que se encontre bem.

A apresentação dos idiomas dos descritores que vêm como resultado da pesquisa no iAHx está aleatória.
Em alguns casos, aparece o Francês, Espanhol da Espanha e Português; em outros, o inglês, o espanhol e o português.

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=G07.738
Nesse exemplo, não aparece o inglês, nem o espanhol.

Tem havido bastante questionamento dos usuários quanto a essa forma de apresentar e eles relatam que o problema acaba aumentando o tempo de consulta por descritores e o número de sites abertos para identificar o descritor desejado. O usuário acaba desistindo de consultar.

Lembro que o problema começou com o teste da API, em colaboração com a desenvolvedora de Cuba. Assim, seria possível informar a ela sobre essa questão e priorizar a ação de reparação?

Muito obrigada!

Para ciência, @Lizbiruel, @lucianaPRB, @alvesmarilda, @suelisuga.

**Comment by viniciusandrade** [comment]
@acecampos boa tarde!

Revisei o código e acredito ter conseguido normalizar a apresentação dos descritores conforme o idioma da interface que esta em uso, exemplos:

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=G07.738

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=es&mode=&tree_id=G07.738

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=en&mode=&tree_id=G07.738

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=fr&mode=&tree_id=G07.738

Quando possível, favor validar.

Obrigado

**Comment by acecampos** [comment]
@viniciusandrade, agradeço a pronta atenção!

Algumas coisas que reparei e que talvez precisassem ser subdivididas em outros issues:

1. A pesquisa na interface em inglês, espanhol e português agora mostra satisfatoriamente o resultado em 3 idiomas. Isso foi constante para os descritores aleatórios buscados. Esse ponto foi validado

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&mode=&tree_id=HP1.007.091

Porém, quando estamos na interface em francês, são mostrados 4 idiomas. 

![image](https://github.com/bireme/Gestao-DeCS/assets/35345406/ee6b5ec4-2141-46f4-8e18-c93226d8d561)

Considerando que o sistema permite mostrar 4 idiomas, poderia mostrar os 4 idiomas quando estivermos em qualquer interface? Creio que fica mais completo e padronizado.

2. No exemplo de descritor [Gnatostomíase](https://pesquisa.bvsalud.org/portal/decs-locator/?lang=fr&mode=&tree_id=C01.610.335.508.700.750.380), encontrado totalmente ao acaso, está faltando o qualificador "[imagerie diagnostique](](https://decs.bvsalud.org/fr/ths/resource/?filter=ths_qualifall&q=&id=56874))", mas ele aparece nos demais idiomas e no portal do DeCS/MeSH: https://decs.bvsalud.org/fr/ths/resource/?id=53934.

![image](https://github.com/bireme/Gestao-DeCS/assets/35345406/9b0b9f61-5db0-41d3-ad63-aa2b60bd7e2c)

3. O francês não é um idioma de pesquisa na linha digitável, mesmo quando estamos na interface em francês. Só é possível encontrar descritores nesse idioma por meio da navegação pela hierarquia ou trocando para lang=fr na url dos outros idiomas. Seria possível corrigir isso?

Estou à disposição para esclarecer melhor essas questões.

Obrigada!

**Comment by viniciusandrade** [comment]
@acecampos, 

Obrigado pela validação do ajuste realizado.
Sobre os itens adicionais mencionados:
1. Você poderia, por gentileza, criar um issue separado para este item no repositório do [iahx](https://github.com/bireme/iahx-opac) e marcar a Rose e a Sueli para ver se elas estão de acordo em adicionarmos os 4 idiomas? Eu particularmente não acho necessidade visto que o uso neste idioma da interface e do FI-ADMIN (indexação) é muito pequeno.

2. OK, ajuste realizado

3. Não temos previsão para esta implementação.
