### ISSUE TITLE
Fornecer token para a API do DeCS - CIAware

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#97]
Prezado @viniciusandrade, por favor, fornecer chave para API do DeCS a ser enviada ao responsável da instituição CIAware, portadora da llicença LEG-2023-0236.

Muito obrigada!

**Comment by viniciusandrade** [comment]
@acecampos chave enviada para seu email, favor verificar. Obrigado.

**Comment by acecampos** [comment]
Obrigada, @viniciusandrade!
