### ISSUE TITLE
Fornecer token para a API do DeCS - Fundación Pública Andaluza Progreso y Salud (Biblioteca Virtual del SSPA)

### ISSUE THREAD

**Issue by acecampos** [bireme/Gestao-DeCS#98]
Prezado @viniciusandrade, por favor, fornecer chave para API do DeCS a ser enviada ao responsável da instituição BVSSPA, detentora da llicença LEG-2023-0263.

Muito obrigada!

para ciência, @lucianaPRB

**Comment by viniciusandrade** [comment]
@acecampos token enviado por email. Abraços.

**Comment by acecampos** [comment]
Obrigada!
